# Generated by Django 4.2.1 on 2023-10-02 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='customer',
            new_name='user',
        ),
    ]
